title: "LeetCode Guide"
description: "A beginner's guide to using LeetCode"
url: "https://yanivgabay.github.io"  
baseurl: "/LeetCodeGuideSite"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-minim
- jekyll-seo-tag  

social_links:
  github: YanivGabay
  linkedin: yaniv-gabayy
  whatsapp: "https://chat.whatsapp.com/IQ3Mghl3NUz09vIdR0t4gd"